// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCpA7io3qYylA4zH1I7LIL94ge7rEXyBo',
    appId: '1:362010586097:web:2e70fe291bdcca6c3f3250',
    messagingSenderId: '362010586097',
    projectId: 'patient-companion-75ea0',
    authDomain: 'patient-companion-75ea0.firebaseapp.com',
    storageBucket: 'patient-companion-75ea0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtTA4_E_5JLVNowGy4SJj7IItgagpTsaA',
    appId: '1:362010586097:android:ab5991727b21f6613f3250',
    messagingSenderId: '362010586097',
    projectId: 'patient-companion-75ea0',
    storageBucket: 'patient-companion-75ea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIvYOfdgbhCGoIEEU53L2yS96_av5D1lE',
    appId: '1:362010586097:ios:325849e0dfaf088c3f3250',
    messagingSenderId: '362010586097',
    projectId: 'patient-companion-75ea0',
    storageBucket: 'patient-companion-75ea0.appspot.com',
    iosClientId: '362010586097-aodpsckvqe5kr1ggqd14k05adfacrsun.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientcompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIvYOfdgbhCGoIEEU53L2yS96_av5D1lE',
    appId: '1:362010586097:ios:325849e0dfaf088c3f3250',
    messagingSenderId: '362010586097',
    projectId: 'patient-companion-75ea0',
    storageBucket: 'patient-companion-75ea0.appspot.com',
    iosClientId: '362010586097-aodpsckvqe5kr1ggqd14k05adfacrsun.apps.googleusercontent.com',
    iosBundleId: 'com.example.patientcompanion',
  );
}
